import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import Container from '@/components/ui/container';
import Header from '@/components/header';
import './globals.css';

const font = Urbanist({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: `Pay 'n Split`,
  description: 'Generated by create next app'
};

//layout that allows parallel pages
export default function RootLayout({
  children,
  friendsModal
}: {
  children: React.ReactNode;
  friendsModal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <Container>
          <Header />
          <div className='px-2 md:px-16'>{children}</div>
        </Container>
        {friendsModal}
      </body>
    </html>
  );
}
